### PR TITLE
Use (recv/send)_bytes instead of recv/send

### PR DESCRIPTION
**Pull request by jvoisin**
This commit improves a bit the performances
in the spirit of b91ad83

### CODE REVIEW

**Comment by yevgenypats** [comment]
hi @jvoisin sorry for dropping the ball on that. can you please sign our standard CLA so I'll be able to merge this?

**Comment by jvoisin** [comment]
Nope.

**Comment by yevgenypats** [comment]
hi @jvoisin I received some heat regarding the CLA and I'm sorry about that, The only thing that I actually wanted is to change it back to standard Apache-2.0 license (instead of current Dual-License) If you are ok with that I will change the license in master and accept all contributions without the CLA (I unlinked the webook). @gerph are you ok going back to Apache-2.0 (I need your approval as well). Thanks for understanding and sorry for that.

**Comment by jvoisin** [comment]
I'm more than happy to switch back to Apache-2.0 :)

**Comment by yevgenypats** [comment]
Thanks @jvoisin . @gerph do you approve this? if Yes - I'll change it right away (I removed all the CLA requirements as there is no need for that in standard Apache-2.0 projects)

**Pull request merged**
